"""001_create_price_records

Revision ID: e28bfb24a59a
Revises: 001
Create Date: 2026-01-31 21:43:05.338277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28bfb24a59a'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_records', 'ticker',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_ticker_created_at'), table_name='price_records')
    op.create_index(op.f('ix_price_records_id'), 'price_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_records_id'), table_name='price_records')
    op.create_index(op.f('ix_ticker_created_at'), 'price_records', ['ticker', 'created_at'], unique=False)
    op.alter_column('price_records', 'ticker',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
